[package]
name = "faux-playground"
version = "0.1.0"
authors = ["Andres <andresnrx@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1"

[dev-dependencies]
faux = "0.1"
futures = "0.3.4"
